name: skript-placeholders
main: com.apickledwalrus.papiaddon.Main
version: 1.1
author: [Pikachu, APickledWalrus]
description: Allows using and registering placeholders with PlaceholderAPI in Skript
website: https://github.com/APickledWalrus/skript-placeholders
depend: [Skript, PlaceholderAPI]
