name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Gradle Wrapper Validation
      uses: gradle/actions/wrapper-validation@v3
    - name: Build with Gradle
      run: ./gradlew nightlyBuild
    - name: Upload Nightly Build
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: skript-placeholders-nightly
        path: build/libs/skript-placeholders-nightly.jar
